// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/rtree/pb/rtree.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinX          float64                `protobuf:"fixed64,1,opt,name=min_x,json=minX,proto3" json:"min_x,omitempty"`
	MaxX          float64                `protobuf:"fixed64,2,opt,name=max_x,json=maxX,proto3" json:"max_x,omitempty"`
	MinY          float64                `protobuf:"fixed64,3,opt,name=min_y,json=minY,proto3" json:"min_y,omitempty"`
	MaxY          float64                `protobuf:"fixed64,4,opt,name=max_y,json=maxY,proto3" json:"max_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_pkg_rtree_pb_rtree_proto_rawDescGZIP(), []int{0}
}

func (x *Rect) GetMinX() float64 {
	if x != nil {
		return x.MinX
	}
	return 0
}

func (x *Rect) GetMaxX() float64 {
	if x != nil {
		return x.MaxX
	}
	return 0
}

func (x *Rect) GetMinY() float64 {
	if x != nil {
		return x.MinY
	}
	return 0
}

func (x *Rect) GetMaxY() float64 {
	if x != nil {
		return x.MaxY
	}
	return 0
}

type Element struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounds        *Rect                  `protobuf:"bytes,1,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_pkg_rtree_pb_rtree_proto_rawDescGZIP(), []int{1}
}

func (x *Element) GetBounds() *Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *Element) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounds        *Rect                  `protobuf:"bytes,1,opt,name=bounds,proto3" json:"bounds,omitempty"`
	IsLeaf        bool                   `protobuf:"varint,2,opt,name=is_leaf,json=isLeaf,proto3" json:"is_leaf,omitempty"`
	Children      []*Node                `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	Elements      []*Element             `protobuf:"bytes,4,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_pkg_rtree_pb_rtree_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetBounds() *Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *Node) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

func (x *Node) GetChildren() []*Node {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Node) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type RTreeProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxEntries    int32                  `protobuf:"varint,1,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	Threshold     float64                `protobuf:"fixed64,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TreeType      string                 `protobuf:"bytes,3,opt,name=tree_type,json=treeType,proto3" json:"tree_type,omitempty"`
	Root          *Node                  `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTreeProto) Reset() {
	*x = RTreeProto{}
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTreeProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTreeProto) ProtoMessage() {}

func (x *RTreeProto) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rtree_pb_rtree_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTreeProto.ProtoReflect.Descriptor instead.
func (*RTreeProto) Descriptor() ([]byte, []int) {
	return file_pkg_rtree_pb_rtree_proto_rawDescGZIP(), []int{3}
}

func (x *RTreeProto) GetMaxEntries() int32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *RTreeProto) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *RTreeProto) GetTreeType() string {
	if x != nil {
		return x.TreeType
	}
	return ""
}

func (x *RTreeProto) GetRoot() *Node {
	if x != nil {
		return x.Root
	}
	return nil
}

var File_pkg_rtree_pb_rtree_proto protoreflect.FileDescriptor

const file_pkg_rtree_pb_rtree_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/rtree/pb/rtree.proto\x12\x05rtree\"Z\n" +
	"\x04Rect\x12\x13\n" +
	"\x05min_x\x18\x01 \x01(\x01R\x04minX\x12\x13\n" +
	"\x05max_x\x18\x02 \x01(\x01R\x04maxX\x12\x13\n" +
	"\x05min_y\x18\x03 \x01(\x01R\x04minY\x12\x13\n" +
	"\x05max_y\x18\x04 \x01(\x01R\x04maxY\"H\n" +
	"\aElement\x12#\n" +
	"\x06bounds\x18\x01 \x01(\v2\v.rtree.RectR\x06bounds\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x99\x01\n" +
	"\x04Node\x12#\n" +
	"\x06bounds\x18\x01 \x01(\v2\v.rtree.RectR\x06bounds\x12\x17\n" +
	"\ais_leaf\x18\x02 \x01(\bR\x06isLeaf\x12'\n" +
	"\bchildren\x18\x03 \x03(\v2\v.rtree.NodeR\bchildren\x12*\n" +
	"\belements\x18\x04 \x03(\v2\x0e.rtree.ElementR\belements\"\x89\x01\n" +
	"\n" +
	"RTreeProto\x12\x1f\n" +
	"\vmax_entries\x18\x01 \x01(\x05R\n" +
	"maxEntries\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x01R\tthreshold\x12\x1b\n" +
	"\ttree_type\x18\x03 \x01(\tR\btreeType\x12\x1f\n" +
	"\x04root\x18\x04 \x01(\v2\v.rtree.NodeR\x04rootB,Z*github.com/riseger/riseger-go/pkg/rtree/pbb\x06proto3"

var (
	file_pkg_rtree_pb_rtree_proto_rawDescOnce sync.Once
	file_pkg_rtree_pb_rtree_proto_rawDescData []byte
)

func file_pkg_rtree_pb_rtree_proto_rawDescGZIP() []byte {
	file_pkg_rtree_pb_rtree_proto_rawDescOnce.Do(func() {
		file_pkg_rtree_pb_rtree_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rtree_pb_rtree_proto_rawDesc), len(file_pkg_rtree_pb_rtree_proto_rawDesc)))
	})
	return file_pkg_rtree_pb_rtree_proto_rawDescData
}

var file_pkg_rtree_pb_rtree_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_rtree_pb_rtree_proto_goTypes = []any{
	(*Rect)(nil),       // 0: rtree.Rect
	(*Element)(nil),    // 1: rtree.Element
	(*Node)(nil),       // 2: rtree.Node
	(*RTreeProto)(nil), // 3: rtree.RTreeProto
}
var file_pkg_rtree_pb_rtree_proto_depIdxs = []int32{
	0, // 0: rtree.Element.bounds:type_name -> rtree.Rect
	0, // 1: rtree.Node.bounds:type_name -> rtree.Rect
	2, // 2: rtree.Node.children:type_name -> rtree.Node
	1, // 3: rtree.Node.elements:type_name -> rtree.Element
	2, // 4: rtree.RTreeProto.root:type_name -> rtree.Node
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_rtree_pb_rtree_proto_init() }
func file_pkg_rtree_pb_rtree_proto_init() {
	if File_pkg_rtree_pb_rtree_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rtree_pb_rtree_proto_rawDesc), len(file_pkg_rtree_pb_rtree_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_rtree_pb_rtree_proto_goTypes,
		DependencyIndexes: file_pkg_rtree_pb_rtree_proto_depIdxs,
		MessageInfos:      file_pkg_rtree_pb_rtree_proto_msgTypes,
	}.Build()
	File_pkg_rtree_pb_rtree_proto = out.File
	file_pkg_rtree_pb_rtree_proto_goTypes = nil
	file_pkg_rtree_pb_rtree_proto_depIdxs = nil
}
