// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/geodata/pb/geodata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeoDataFile 是 .geodata 二进制文件的顶层结构。
// 一个文件可以包含多个数据库定义。
type GeoDataFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []*GeoDatabase         `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoDataFile) Reset() {
	*x = GeoDataFile{}
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoDataFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoDataFile) ProtoMessage() {}

func (x *GeoDataFile) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoDataFile.ProtoReflect.Descriptor instead.
func (*GeoDataFile) Descriptor() ([]byte, []int) {
	return file_pkg_geodata_pb_geodata_proto_rawDescGZIP(), []int{0}
}

func (x *GeoDataFile) GetDatabases() []*GeoDatabase {
	if x != nil {
		return x.Databases
	}
	return nil
}

type GeoDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Configs       map[string]string      `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Models        []*GeoModel            `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	Maps          []*GeoMap              `protobuf:"bytes,4,rep,name=maps,proto3" json:"maps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoDatabase) Reset() {
	*x = GeoDatabase{}
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoDatabase) ProtoMessage() {}

func (x *GeoDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoDatabase.ProtoReflect.Descriptor instead.
func (*GeoDatabase) Descriptor() ([]byte, []int) {
	return file_pkg_geodata_pb_geodata_proto_rawDescGZIP(), []int{1}
}

func (x *GeoDatabase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeoDatabase) GetConfigs() map[string]string {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *GeoDatabase) GetModels() []*GeoModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *GeoDatabase) GetMaps() []*GeoMap {
	if x != nil {
		return x.Maps
	}
	return nil
}

type GeoModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent        string                 `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key -> FieldType name ("STRING", "DOUBLE", etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoModel) Reset() {
	*x = GeoModel{}
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoModel) ProtoMessage() {}

func (x *GeoModel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoModel.ProtoReflect.Descriptor instead.
func (*GeoModel) Descriptor() ([]byte, []int) {
	return file_pkg_geodata_pb_geodata_proto_rawDescGZIP(), []int{2}
}

func (x *GeoModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeoModel) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *GeoModel) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GeoMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NodeSize      int32                  `protobuf:"varint,2,opt,name=node_size,json=nodeSize,proto3" json:"node_size,omitempty"`
	Threshold     float64                `protobuf:"fixed64,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Elements      []*GeoElement          `protobuf:"bytes,4,rep,name=elements,proto3" json:"elements,omitempty"`
	Submaps       []*GeoSubmap           `protobuf:"bytes,5,rep,name=submaps,proto3" json:"submaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoMap) Reset() {
	*x = GeoMap{}
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoMap) ProtoMessage() {}

func (x *GeoMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoMap.ProtoReflect.Descriptor instead.
func (*GeoMap) Descriptor() ([]byte, []int) {
	return file_pkg_geodata_pb_geodata_proto_rawDescGZIP(), []int{3}
}

func (x *GeoMap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeoMap) GetNodeSize() int32 {
	if x != nil {
		return x.NodeSize
	}
	return 0
}

func (x *GeoMap) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *GeoMap) GetElements() []*GeoElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *GeoMap) GetSubmaps() []*GeoSubmap {
	if x != nil {
		return x.Submaps
	}
	return nil
}

type GeoSubmap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ScopePath     string                 `protobuf:"bytes,2,opt,name=scope_path,json=scopePath,proto3" json:"scope_path,omitempty"`
	Elements      []*GeoElement          `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`
	Submaps       []*GeoSubmap           `protobuf:"bytes,4,rep,name=submaps,proto3" json:"submaps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSubmap) Reset() {
	*x = GeoSubmap{}
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSubmap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSubmap) ProtoMessage() {}

func (x *GeoSubmap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSubmap.ProtoReflect.Descriptor instead.
func (*GeoSubmap) Descriptor() ([]byte, []int) {
	return file_pkg_geodata_pb_geodata_proto_rawDescGZIP(), []int{4}
}

func (x *GeoSubmap) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GeoSubmap) GetScopePath() string {
	if x != nil {
		return x.ScopePath
	}
	return ""
}

func (x *GeoSubmap) GetElements() []*GeoElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *GeoSubmap) GetSubmaps() []*GeoSubmap {
	if x != nil {
		return x.Submaps
	}
	return nil
}

type GeoElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ParentModel   string                 `protobuf:"bytes,2,opt,name=parent_model,json=parentModel,proto3" json:"parent_model,omitempty"`                                                      // "point", "road", "field"
	Coords        []*GeoCoord            `protobuf:"bytes,3,rep,name=coords,proto3" json:"coords,omitempty"`                                                                                   // 空间坐标点列表
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 非空间属性 key -> string value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoElement) Reset() {
	*x = GeoElement{}
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoElement) ProtoMessage() {}

func (x *GeoElement) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoElement.ProtoReflect.Descriptor instead.
func (*GeoElement) Descriptor() ([]byte, []int) {
	return file_pkg_geodata_pb_geodata_proto_rawDescGZIP(), []int{5}
}

func (x *GeoElement) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GeoElement) GetParentModel() string {
	if x != nil {
		return x.ParentModel
	}
	return ""
}

func (x *GeoElement) GetCoords() []*GeoCoord {
	if x != nil {
		return x.Coords
	}
	return nil
}

func (x *GeoElement) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type GeoCoord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoCoord) Reset() {
	*x = GeoCoord{}
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoCoord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoCoord) ProtoMessage() {}

func (x *GeoCoord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_geodata_pb_geodata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoCoord.ProtoReflect.Descriptor instead.
func (*GeoCoord) Descriptor() ([]byte, []int) {
	return file_pkg_geodata_pb_geodata_proto_rawDescGZIP(), []int{6}
}

func (x *GeoCoord) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GeoCoord) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_pkg_geodata_pb_geodata_proto protoreflect.FileDescriptor

const file_pkg_geodata_pb_geodata_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/geodata/pb/geodata.proto\x12\ageodata\"A\n" +
	"\vGeoDataFile\x122\n" +
	"\tdatabases\x18\x01 \x03(\v2\x14.geodata.GeoDatabaseR\tdatabases\"\xea\x01\n" +
	"\vGeoDatabase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\aconfigs\x18\x02 \x03(\v2!.geodata.GeoDatabase.ConfigsEntryR\aconfigs\x12)\n" +
	"\x06models\x18\x03 \x03(\v2\x11.geodata.GeoModelR\x06models\x12#\n" +
	"\x04maps\x18\x04 \x03(\v2\x0f.geodata.GeoMapR\x04maps\x1a:\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x01\n" +
	"\bGeoModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12A\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2!.geodata.GeoModel.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x06GeoMap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tnode_size\x18\x02 \x01(\x05R\bnodeSize\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x01R\tthreshold\x12/\n" +
	"\belements\x18\x04 \x03(\v2\x13.geodata.GeoElementR\belements\x12,\n" +
	"\asubmaps\x18\x05 \x03(\v2\x12.geodata.GeoSubmapR\asubmaps\"\x9d\x01\n" +
	"\tGeoSubmap\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"scope_path\x18\x02 \x01(\tR\tscopePath\x12/\n" +
	"\belements\x18\x03 \x03(\v2\x13.geodata.GeoElementR\belements\x12,\n" +
	"\asubmaps\x18\x04 \x03(\v2\x12.geodata.GeoSubmapR\asubmaps\"\xfd\x01\n" +
	"\n" +
	"GeoElement\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12!\n" +
	"\fparent_model\x18\x02 \x01(\tR\vparentModel\x12)\n" +
	"\x06coords\x18\x03 \x03(\v2\x11.geodata.GeoCoordR\x06coords\x12C\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2#.geodata.GeoElement.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\bGeoCoord\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01yB.Z,github.com/riseger/riseger-go/pkg/geodata/pbb\x06proto3"

var (
	file_pkg_geodata_pb_geodata_proto_rawDescOnce sync.Once
	file_pkg_geodata_pb_geodata_proto_rawDescData []byte
)

func file_pkg_geodata_pb_geodata_proto_rawDescGZIP() []byte {
	file_pkg_geodata_pb_geodata_proto_rawDescOnce.Do(func() {
		file_pkg_geodata_pb_geodata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_geodata_pb_geodata_proto_rawDesc), len(file_pkg_geodata_pb_geodata_proto_rawDesc)))
	})
	return file_pkg_geodata_pb_geodata_proto_rawDescData
}

var file_pkg_geodata_pb_geodata_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_geodata_pb_geodata_proto_goTypes = []any{
	(*GeoDataFile)(nil), // 0: geodata.GeoDataFile
	(*GeoDatabase)(nil), // 1: geodata.GeoDatabase
	(*GeoModel)(nil),    // 2: geodata.GeoModel
	(*GeoMap)(nil),      // 3: geodata.GeoMap
	(*GeoSubmap)(nil),   // 4: geodata.GeoSubmap
	(*GeoElement)(nil),  // 5: geodata.GeoElement
	(*GeoCoord)(nil),    // 6: geodata.GeoCoord
	nil,                 // 7: geodata.GeoDatabase.ConfigsEntry
	nil,                 // 8: geodata.GeoModel.ParametersEntry
	nil,                 // 9: geodata.GeoElement.AttributesEntry
}
var file_pkg_geodata_pb_geodata_proto_depIdxs = []int32{
	1,  // 0: geodata.GeoDataFile.databases:type_name -> geodata.GeoDatabase
	7,  // 1: geodata.GeoDatabase.configs:type_name -> geodata.GeoDatabase.ConfigsEntry
	2,  // 2: geodata.GeoDatabase.models:type_name -> geodata.GeoModel
	3,  // 3: geodata.GeoDatabase.maps:type_name -> geodata.GeoMap
	8,  // 4: geodata.GeoModel.parameters:type_name -> geodata.GeoModel.ParametersEntry
	5,  // 5: geodata.GeoMap.elements:type_name -> geodata.GeoElement
	4,  // 6: geodata.GeoMap.submaps:type_name -> geodata.GeoSubmap
	5,  // 7: geodata.GeoSubmap.elements:type_name -> geodata.GeoElement
	4,  // 8: geodata.GeoSubmap.submaps:type_name -> geodata.GeoSubmap
	6,  // 9: geodata.GeoElement.coords:type_name -> geodata.GeoCoord
	9,  // 10: geodata.GeoElement.attributes:type_name -> geodata.GeoElement.AttributesEntry
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_geodata_pb_geodata_proto_init() }
func file_pkg_geodata_pb_geodata_proto_init() {
	if File_pkg_geodata_pb_geodata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_geodata_pb_geodata_proto_rawDesc), len(file_pkg_geodata_pb_geodata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_geodata_pb_geodata_proto_goTypes,
		DependencyIndexes: file_pkg_geodata_pb_geodata_proto_depIdxs,
		MessageInfos:      file_pkg_geodata_pb_geodata_proto_msgTypes,
	}.Build()
	File_pkg_geodata_pb_geodata_proto = out.File
	file_pkg_geodata_pb_geodata_proto_goTypes = nil
	file_pkg_geodata_pb_geodata_proto_depIdxs = nil
}
